# permissions for end users to view connectionmongoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connectionmongo-viewer-role
rules:
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmongoes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmongoes/status
    verbs:
      - get
