# permissions for end users to view connectionmysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connectionmysql-viewer-role
rules:
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmysqls
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmysqls/status
    verbs:
      - get
