# permissions for end users to edit externalpostgres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalpostgres-editor-role
rules:
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalpostgres
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalpostgres/status
    verbs:
      - get
