# permissions for end users to view externalmysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalmysql-viewer-role
rules:
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmysqls
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmysqls/status
    verbs:
      - get
