# permissions for end users to view externalmongoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalmongo-viewer-role
rules:
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmongoes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmongoes/status
    verbs:
      - get
