---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmongoes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmongoes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmysqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionmysqls/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionpostgres
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - connectionpostgres/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmongoes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmongoes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmysqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalmysqls/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalpostgres
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - externaldb.databases.land
    resources:
      - externalpostgres/status
    verbs:
      - get
      - patch
      - update
